# Workflow of how agents run?
# When we run this code, all tools are loaded to the LLM.
# Then based on the input, LLM decides which tool(function) to invoke, with what arguments
# LangChain then invokes that tool (function) with the arguments provided by the LLM and gets the result.
# Then LLM can use the result of the tool to generate the final response.

from dotenv import load_dotenv
load_dotenv()

from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_ollama import ChatOllama
# from tavily import TavilyClient

# This is the updated class referred to by Documentation
# This TavilySearch is also a Tool (function), that means it can be directly passed to the Agent, and agent will use this to search the web.
from langchain_tavily import TavilySearch

# This is the way to create custom tools using also about, how to use tavily directly.
# @tool
# def search(query: str) -> str:
#     """
#     Tool that searches over internet
#     Args:
#         query (str): The query to search for
#     Returns:
#         str: The search results
#     """
#     print(f"Searching for: {query}")
#     return tavily.search(query=query)

# ======================================================================================================================

# Converting LLM Response into structured format
from typing import List

# Pydantic is a data validation and settings management library for Python, based on type annotations.
# It allows you to define data models with type hints and provides validation and parsing of input data.
from pydantic import BaseModel, Field

class Source(BaseModel):
    """Schema for a source used by the agent"""
    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    """Schema for agent response with answer and sources"""
    answer: str = Field(description="The agents answer to the query")
    sources: List[Source] = Field(default_factory=list,description="The sources used to answer the query")





def main():
    print("Hello, World!")
    result = agent.invoke({"messages": HumanMessage(content="What is the weather in Tokyo?")})
    # This result variable is an array of sequence of events happened during the execution of the agent.
    # It contains the messages exchanged between the LLM and the tools, as well as the final response
    # generated by the LLM after using the tools. Each element in the result array represents a step in
    # the agent's reasoning process, including tool invocations and their outputs.

    # For the current example, the result will contain only 4 messages.
    # 1. The first message will be the HumanMessage with the content "What is the weather in Tokyo?".
    # 2. The second message will be the LLM's response to the HumanMessage, which will be a message indicating that it is invoking the search tool with the query "What is the weather in Tokyo?".
    # 3. The third message will be the output of the search tool, which will be "Tokyo weather is sunny".
    # 4. The fourth message will be the final response generated by the LLM after using the search tool, which will be "The weather in Tokyo is sunny."
    print(result)

# tavily = TavilyClient() Tavily SDK

llm = ChatOllama(model="qwen3-coder:30b", temperature=0)
# tools = [search] # Replace this with TavilySearch tool
tools = [TavilySearch()]
# To format the response of the agent, we pass another field
agent = create_agent(llm, tools, agent=AgentResponse)


if __name__ == "__main__":
    main()
